# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randWrapper <- function(n) {
    .Call('_carsimr_rios_randWrapper', PACKAGE = 'carsimr.rios', n)
}

random_shuffle_cpp <- function(a) {
    .Call('_carsimr_rios_random_shuffle_cpp', PACKAGE = 'carsimr.rios', a)
}

#' @rdname initialize_grid
#' @export
initialize_grid_cpp <- function(rho, dims, prob_blue) {
    .Call('_carsimr_rios_initialize_grid_cpp', PACKAGE = 'carsimr.rios', rho, dims, prob_blue)
}

move_blue_cpp <- function(t_grid) {
    .Call('_carsimr_rios_move_blue_cpp', PACKAGE = 'carsimr.rios', t_grid)
}

move_red_cpp <- function(t_grid) {
    .Call('_carsimr_rios_move_red_cpp', PACKAGE = 'carsimr.rios', t_grid)
}

#' @rdname move_cars
#' @export
move_cars_cpp <- function(t_grid, trials) {
    .Call('_carsimr_rios_move_cars_cpp', PACKAGE = 'carsimr.rios', t_grid, trials)
}

